### ISSUE TITLE
Min versión PHP requerid ..?

### ISSUE THREAD

**Issue by EOM** [faisalman/simple-excel-php#40]
Min versión PHP requerid ..?
Not show in Doc **readme.md**

**Comment by davidjeddy** [comment]
IIRC the library will work on PHP 5.4+, to be honest no one should be using > 5.4 in production for security reasons anyways.

**Comment by EOM** [comment]
Hi, as developers, we do not have to think about tasks that belong to the system administrator. You just have to do the right thing. 
If the library was developed for PHP 5.x or higher, it has to be documented. 
As developers, you do not have to assume tasks from other areas.
Is the right way to do our work as developers to have a job with more quality.

**Comment by davidjeddy** [comment]
@EOM PR created and submitted. Thank you for the input.

**Comment by faisalman** [comment]
Minimum PHP version:
- 5.3 for v0.3 & v0.4
- 7.0 for v0.5
