### ISSUE TITLE
Non-Excel XML to Excel?

### ISSUE THREAD

**Issue by skazhikadyadya** [faisalman/simple-excel-php#44]
Hello. I try to use SimpleExcel for parsing and convert non-Excel XML file. When I try to do it I get that error: "Document namespace isn't a valid Excel XML 2003 Spreadsheet".

Can I use SimpleExcel for create .xls documents from non Excel XML? Thanks.

**Comment by davidjeddy** [comment]
I would lean towards not, as the library is not created for that type of functionality.

**Comment by faisalman** [comment]
Unfortunately no, as we can't identify which elements go where without a standard schema..
