### ISSUE TITLE
Class 'SimpleExcel' not found

### ISSUE THREAD

**Issue by Bert-de-Jong** [faisalman/simple-excel-php#53]
I'm running into the same problem as mentioned by Nevega on linux.org.ru [here](https://www.linux.org.ru/forum/web-development/13328694).
Namely an error "Class 'SimpleExcel' not found".
```php
<?php
  error_reporting (-1);
  ini_set ('display_errors', 'On');
  include_once (dirname (__FILE__) . '/../lib/SimpleExcel/SimpleExcel.php');
  $excel = new SimpleExcel ('xml');
?>
```
The include works, but then the new fails.

**Comment by guyilherme** [comment]
I have the same problem

**Comment by cfoellmann** [comment]
You need 

```php
use SimpleExcel\SimpleExcel;

```
because the class is in its own namespace

**Comment by Bert-de-Jong** [comment]
> You need
> 
> ```
> use SimpleExcel\SimpleExcel;
> ```
> 
> because the class is in its own namespace

Going by the examples for [0.3.x](https://faisalman.github.io/simple-excel-php/api/0.3/) and [0.4.x](https://faisalman.github.io/simple-excel-php/), what you write is correct.
Even the README [mentions](https://github.com/faisalman/simple-excel-php/blob/master/readme.md#usage) it.
I have no idea why I didn't include the use statement.
Maybe the documentation has changed or is now more easily accessible, or something.
I already switched to PhpSpreadsheet since I created this issue (ticket/thread), so I cannot check my code to see what I was trying to do at the time.
I'm closing this issue.

**Comment by cfoellmann** [comment]
I just started using PhpSpreadsheet myself. Working wiht an xls as a "database" is a real pain. but a requirement in my case
